name: PR Checks
 
on:
  pull_request:
 
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cargo test
        run: cargo test
