name: PR Checks
 
on:
  pull_request:
 
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cargo test
        run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Add rustfmt and clippy
        run: rustup component add rustfmt clippy
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
