name: PR Checks
 
on:
  pull_request:
 
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cargo test
        run: cargo test

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Add clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
