name: Deply to crates.io

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cargo test
        run: cargo test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Deploy to crates.io
        run: cargo publish
